name: DoublePluginSkill-1.16.5
main: doublePluginSkill.DoublePluginSkill
version: 1.0
api-version: 1.16
depend: [DoublePlugin-1.16.5]

commands:  
  skill: 
    description: use skill
    aliases: [스킬]
    permission: DoublePluginSystem
    permission-message: 당신은 이 명령어를 사용할 권한이 존재하지 않습니다!
    
permissions:
  DoublePluginSkillSystem:
   default: op